use_frameworks!

target 'ColorScreen_Example' do
  platform :ios, '12.0'

  pod 'ColorScreen', :path => '../'
  pod 'ColorSlider'
  pod 'RxSwift', '~> 5.0.0'
  pod 'RxCocoa', '~> 5.0.0'
  pod 'SnapKit'
  pod 'DynamicColor'
  pod 'Firebase/Core'
  pod 'RxFirebase/Database'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'DeviceKit'
  pod 'SwiftyButton'
  pod 'MultiPeer'

  pod 'SwiftFormat/CLI'
  pod 'SwiftySound'
  pod 'iBeaconManager'

  pod 'RxBluetoothKit'


  script_phase :name => 'swiftformat run', :script => ' ./Pods/SwiftFormat/CommandLineTool/swiftformat .', :execution_position => :before_compile

  target 'ColorScreen_Tests' do
    inherit! :search_paths
  end
end
